repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.7
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    - id: flake8
-   repo: local
    hooks:
    - id: jupytext
      name: jupytext
      entry: python scripts/pre_commit_jupytext.py
      language: system
      files: \.ipynb$
